site_name: Grupo B - UAM
site_url: https://betina-boop.github.io/Grupo-B/

theme: readthedocs
name: mkdocs
locale: pt


nav:
  - Home: index.md
  - Integrantes: integrantes.md
  - Projeto de Vertiporto: atividade1.md
  - Referências: referencias.md


  
markdown_extensions:
  toc:
    permalink: true
  admonition: {}